theme: minima

title: Katie's Adventures In Clay
description: >- # this means to ignore newlines until "baseurl:"
  Follow along as Katie explores the world of creating pottery.

instagram_username: katiesadventuresinclay
